FORMAT: 1A
HOST: http://api.apps.example.com

# App Store API
The App Store API is a service that provides affordances to explore and install applications available on the App Store.

**NOTE: This document is a work in progress**

# Authentication

TBD

# Media Types

Where applicable this API uses the *text/html* media-type to represent resource states and affordances.

Requests with a message-body are using *application/x-www-form-urlencoded* to set or update resource states.

# Error States

The common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used.


# App Store API Root [/]
App Store API entry point.

This resource does not have any attributes. Instead it offers the initial API affordances in the form of HTML links. 
For convenience it will **embed** two collections representing *new* and *featured* applications.

The available affordances are defined by the relations:

- index [HTML4]
- canonical [RFC6596]
- collection [RFC6573]

## Retrieve entry point [GET]

+ Response 200 (text/html)

    + Body
    
            <html>
                <body>
                    <div id="links">
                        <ul>
                            <li><a rel="index" href="/" title="Home page">Home</a></li>
                        </ul>
                    </div>
                    <div id="embedded">
                        <ul>
                            <li>
                                <div class="app-list">
                                    <a rel="collection" name="featured" href="/apps/featured" title="Featured apps">Featured</a>
                                    <ul>
                                        <li class="app">
                                            <a rel="canonical" class="name" href="/apps/1" title="app details">
                                                <span class="name">Name</span>
                                                <span class="author:name">John Doe</span>
                                                <span class="price">
                                                    <span class="amount">0.00</span>
                                                    <span class="currency">USD</span>
                                                </span>
                                                <ul class="icons">
                                                    <li><img width="256px" height="256px" src="http://www.example.com/icon256.png" /></li>
                                                </ul>
                                            </a>
                                        </li>
                                        <li class="app">
                                            <a rel="canonical" class="name" href="/apps/2" title="app details">
                                                <span class="name">Other</span>
                                                <span class="author:name">Jane Doe</span>
                                                <span class="price">
                                                    <span class="amount">0.00</span>
                                                    <span class="currency">USD</span>
                                                </span>
                                                <ul class="icons">
                                                    <li><img width="256px" height="256px" src="http://www.example.com/icon256.png" /></li>
                                                </ul>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            <li>
                                <div class="app-list">
                                    <a rel="collection" name="new" href="/apps/new" title="New apps">New releases</a>
                                    <ul>
                                        <li class="app">
                                            <a rel="canonical" class="name" href="/apps/1" title="app details">
                                                <span class="name">Name</span>
                                                <span class="author:name">John Doe</span>
                                                <span class="price">
                                                    <span class="amount">0.00</span>
                                                    <span class="currency">USD</span>
                                                </span>
                                                <ul class="icons">
                                                    <li><img width="256px" height="256px" src="http://www.example.com/icon256.png" /></li>
                                                </ul>
                                            </a>
                                        </li>
                                        <li class="app">
                                            <a rel="canonical" class="name" href="/apps/2" title="app details">
                                                <span class="name">Other</span>
                                                <span class="author:name">Jane Doe</span>
                                                <span class="price">
                                                    <span class="amount">0.00</span>
                                                    <span class="currency">USD</span>
                                                </span>
                                                <ul class="icons">
                                                    <li><img width="256px" height="256px" src="http://www.example.com/icon256.png" /></li>
                                                </ul>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            <li>Categories
                              <ul class="categories">
                                <li><a rel="collection" class="category" name="Games" href="/apps?category=Games" title="Games">Games</a></li>
                                <li><a rel="collection" class="category" name="Finance" href="/apps?category=Finance" title="Finance">Finance</a></li>
                                <li><a rel="collection" class="category" name="Productivity" href="/apps?category=Productivity" title="Productivity">Productivity</a></li>
                              </ul>
                            </li>
                        </ul>
                    </div>
                    <div id="queries">
                        <form method="get" action="/search" name="search">
                            <input type="text" name="q" value="" />
                            <input type="submit" value="Search" />
                        </form>
                    </div>
                </body>
            </html>

# Group App
App-related resources of *App Store API*

## App [/apps/{id}]
A single App. The App is the central resource in the *App Store API*. It represents one application.

The App resource has the following attributes:

- name
- author
- license
- date_published
- description
- changelog
- version
- binary-filesize
- icons
- screenshots
- tags
- price

An App has affordances defined by the relations:

- canonical [RFC6596]
- collection [RFC6573]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the App to perform action with. Has example value.

+ Model (text/html)

    HTML representation of App resource. In addition to representing it's state using a microformat in HTML, it offers affordances in the form of the HTTP Link header and HTML links. 
    
    + Body
    
            <html>
                <body>
                    <div class="app-list">
                      <ul>
                        <li class="app">
                          <a rel="canonical" class="name" href="/apps/1">Name</a>
                          <a rel="collection" class="author" href="/apps?author=John+Doe" title="apps from same author">John Doe</a>
                          <a rel="collection" class="category" name="Accessories" href="/apps?category=Accessories" title="Accessories">Accessories</a>
                          <span class="date-published">2014-02-04</span>
                          <span class="price">
                            <span class="amount">0.00</span>
                            <span class="currency">USD</span>
                          </span>
                          <span class="description">The description</span>
                          <ul class="icons">
                            <li><img width="256px" height="256px" src="http://www.example.com/icon256.png" /></li>
                            <li><img width="64px" height="64px" src="http://www.example.com/icon64.png" /></li>
                          </ul>
                          <ul class="screenshots">
                            <li><img width="800px" height="600px" src="http://www.example.com/screenshot-desktop.jpg" /></li>
                            <li><img width="220px" height="400px" src="htpp://www.example.com/screenshot-mobile.jpg" /></li>
                          </ul>
                          <ul class="tags">
                            <li><a rel="collection" class="tag" href="/apps?tag=foo">foo</a></li>
                            <li><a rel="collection" class="tag" href="/apps?tag=bar">bar</a></li>
                          </ul>
                          <span class="license">GPLv3</span>
                          <span class="changelog">A list of changes</span>
                          <span class="binary-filesize">12345678</span>
                          <span class="version">0.1</span>
                          <a class="author:website" href="http://www.example.com">Go to author website</a>
                          <a class="author:email" href="mailto:foo@example.com">Email author</a>
                        </li>
                      </ul>
                    </div>
                </body>
            </html>

### Retrieve an App [GET]
+ Response 200

    [App][]
    
## App List [/apps{?tag,category,author}]
Collection of all Apps.

This resource **embeds** a simplified representation for each *App Resource* in the *App Store API*.

+ Parameters

    + tag (optional, string) ... Value of tag to use for filtering apps
    + category (optional, string) ... Value of category to use for filtering apps
    + author (optional, string) ... Value of author to use for filtering apps

+ Model (text/html)

    HTML representation of App Collection Resource. The App resources in collections are embedded. Note the embedded App resource are incomplete representations of the App in question. Use the respective App link to retrieve its full representation.

    + Body

            <html>
                <body>
                    <div id="app-list">
                      <ul>
                        <li class="app">
                          <a rel="canonical" class="name" href="/apps/1" title="app details">
                            <span class="name">Name</span>
                            <span class="author:name">John Doe</span>
                            <span class="price">
                              <span class="amount">0.00</span>
                              <span class="currency">USD</span>
                            </span>
                            <ul class="icons">
                              <li><img width="256px" height="256px" src="http://www.example.com/icon256.png" /></li>
                            </ul>
                          </a>
                        </li>
                        <li class="app">
                          <a rel="canonical" class="name" href="/apps/2" title="app details">
                            <span class="name">Other</span>
                            <span class="author:name">Jane Doe</span>
                            <span class="price">
                              <span class="amount">0.00</span>
                              <span class="currency">USD</span>
                            </span>
                            <ul class="icons">
                              <li><img width="256px" height="256px" src="http://www.example.com/icon256.png" /></li>
                            </ul>
                          </a>
                        </li>
                      </ul>
                    </div>
                </body>
            </html>

### List all apps [GET]
+ Response 200

    [App List][]
